# Base configs
# If testing locally, comment the baseurl below and uncomment the blank one
baseurl: "/photography"
# baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""  # Optional: Add your GA4 ID if you have one (e.g., G-XXXXXXXXXX)

# UI configs
title: "Photography by Brayden Noh"
subtitle: "See the world through my eyes"
author: "Brayden Noh"

header:
  title: "Photography"
  subtitle: "by Brayden Noh"

footer:
  name: "Brayden Noh"
  bio: 
  github: "Made using <a href=\"https://github.com/braydennoh/photography\">this open-source template</a>"
web_design: "AJ"

# Configure which EXIF data to display
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'

# Social media links (customize as needed)
social_urls:
  twitter: ""  # Add yours if you want
  instagram: "https://www.instagram.com/braydennoh"
  dribbble: ""
  linkedin: "https://www.linkedin.com/in/braydennoh"
  github: "https://www.github.com/braydennoh"
